version: "3"

services:
  jupyter:
    container_name: client-jupyter
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - .:/notebooks
    environment:
      - GRANT_SUDO=yes
    user: root
