services:
  jupyter:
    container_name: client-jupyter
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - .:/notebooks
    environment:
      - GRANT_SUDO=yes
    user: root
    command: bash -c "echo 'Starting Jupyter Lab...' && conda run -n myenv jupyter lab --ip=0.0.0.0 --allow-root"
